const options = {
  printWidth: 80,
  tabWidth: 2,
  endOfLine: 'lf',
  useTabs: false,
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  arrowParens: 'avoid',
  parser: 'babylon',
  plugins: [
    'jsx',
    'flowtype',
    'flow',
    'asyncFunctions',
    'classProperties',
    'objectRestSpread',
    'decorators',
    'decorators-legacy',
    'doExpressions',
    'exponentiationOperator',
    'exportExtensions',
    'functionBind',
    'functionSent',
  ],
};

module.exports = options;
